### ISSUE TITLE
Rank deficiency handling for GUI mode

### ISSUE THREAD

**Issue by parikshitbajpai** [ORNL-CEES/thermochimica#59] opened 2021-09-30 18:31 UTC
## Description
In cases like the NiF2-KF system the database setup results in a rank deficient stoichiometric matrix causing a failure to converge. A compound mode was implemented in Thermochimica but is not supported in GUI. Such failures don't happen in FactSage and users not aware of the underlying issue might think that the code does not work. We should figure out a way of handling such rank deficiency whether it is using the compound mode or some other way.

## Impact
Improved range of application. Increase user confidence

**Comment by maxposchmann** [comment] 2021-10-04 16:13
Clearly there is something here to look at, but I am not sure that this failure is caused by the rank deficiency. They same system as noted in the other issue (0.2 Ni, 0.8 K, 1.2 F) converges to reasonable results in the temperature interval 1100 K to 3000 K (maybe above too).

Maybe the low-temperature NiKF example should be a separate issue, and this one should get a better example where this is definitely the cause?

**Comment by maxposchmann** [comment] 2021-10-06 17:10
Looks to be resolved for this system in 3457fb9d4409bc5c4ecc627f338653a06e9e8932.

CI runs on this branch suggest I haven't left anything broken with these changes. However they are pretty significant so perhaps further testing should be required. Other rank-deficient cases in particular would be good to test.

Tests should be added to test/daily for rank-deficient cases to solidify this improvement.

**Comment by maxposchmann** [comment] 2022-12-05 21:15
Closed by #117

**Closed by maxposchmann** 2022-12-05 21:15 UTC
Labels: enhancement
